version: '3.5'
services:
  flask:
    image: my-flask-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    ports:
      - "5000:5000"
    command: python -m flask run --debugger --reload --host=0.0.0.0
    depends_on:
      - db
  
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d